# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c27b41a951cd7d9fb3c081ef3be34444ef3be5524f452e6894896a6d404d734ae243b266a7424a1341feada2fe5b63d3e1ad27b6a015a1771cfd54ca5e77b3b5

test:
  secret_key_base: 2616efbf6aa3d325798bd1d78f8dd28a654f27735bdbc9dcb77d39b0de32ecccfc151cb0cbcfc3c3ad4658a74bb0c3ec6521afdd7a99cf6b3802414937b2d7f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
